services:
  postgres:
    image: postgres:15
    container_name: postgres-notifs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: notifs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data1
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: ppp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend


volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
